spring:
  application:
    name: otoken-web-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false         # 开发时关闭缓存
    mode: LEGACYHTML5    # 使用非严格的HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

feign:
  hystrix:
    enabled: true

server:
  port: 8601

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info